runtime: python310
entrypoint: gunicorn -b :$PORT app:app

# Opcional: Ajustes de recursos para ahorrar costos en pruebas
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1
